
ALTER TABLE t_p7851806_project_inovation_la.admins
  ADD COLUMN IF NOT EXISTS vk_id VARCHAR(50),
  ADD COLUMN IF NOT EXISTS vk_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS vk_avatar VARCHAR(500),
  ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'editor',
  ADD COLUMN IF NOT EXISTS approved BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS approved_by VARCHAR(50);

CREATE UNIQUE INDEX IF NOT EXISTS admins_vk_id_unique ON t_p7851806_project_inovation_la.admins(vk_id) WHERE vk_id IS NOT NULL;
